- name: Hello World HTML Sample  
  hosts: all  
  become: yes  # 指示 Ansible 使用 sudo/su 来执行接下来的任务  
  become_user: root  # 明确指定使用 root 用户来执行  
  tasks:  
    - name: Create Hello World HTML file  
      copy:  
        content: "<html><body><h1>Hello World!</h1></body></html>"  
        dest: /root/file.html  # 替换为你想要的路径和文件名  
        mode: '0644'  # 设置文件权限为 644（所有者读/写，组和其他读）
